@echo off
REM Script para organizar archivos automáticamente
REM Ejecutar desde: c:\Users\acer\3Warner

cd /d c:\Users\acer\3Warner

REM INICIO RÁPIDO - LOS MÁS NUEVOS
if exist RESUMEN_VISUAL_FINAL.txt move RESUMEN_VISUAL_FINAL.txt 01_INICIO_RAPIDO_LECTURA_INMEDIATA\
if exist CONCLUSION_Y_PROXIMOS_PASOS.md move CONCLUSION_Y_PROXIMOS_PASOS.md 01_INICIO_RAPIDO_LECTURA_INMEDIATA\
if exist RESUMEN_SESION_ENTREGA.md move RESUMEN_SESION_ENTREGA.md 01_INICIO_RAPIDO_LECTURA_INMEDIATA\
if exist INDICE_MAESTRO_SESION.md move INDICE_MAESTRO_SESION.md 01_INICIO_RAPIDO_LECTURA_INMEDIATA\
if exist 00_LEEME_PRIMERO.md move 00_LEEME_PRIMERO.md 01_INICIO_RAPIDO_LECTURA_INMEDIATA\

REM PLANIFICACIÓN Y ROADMAP
if exist PLAN_IMPLEMENTACION_MEJORAS_OOLALE.md move PLAN_IMPLEMENTACION_MEJORAS_OOLALE.md 02_PLANIFICACION_ROADMAP\
if exist PROJECT_STATUS.md move PROJECT_STATUS.md 02_PLANIFICACION_ROADMAP\
if exist PLAN_ACCION_30_DIAS.md move PLAN_ACCION_30_DIAS.md 02_PLANIFICACION_ROADMAP\
if exist ANTES_DESPUES.md move ANTES_DESPUES.md 02_PLANIFICACION_ROADMAP\

REM CÓDIGO FLUTTER
if exist portfolio_screen.dart move portfolio_screen.dart 03_CODIGO_FLUTTER_LISTO\
if exist ratings_screen.dart move ratings_screen.dart 03_CODIGO_FLUTTER_LISTO\
if exist upload_media_screen.dart move upload_media_screen.dart 03_CODIGO_FLUTTER_LISTO\

REM CÓDIGO BACKEND
if exist ENDPOINTS_FASE_1_2.js move ENDPOINTS_FASE_1_2.js 04_CODIGO_BACKEND_LISTO\
if exist test-api-completo.js move test-api-completo.js 04_CODIGO_BACKEND_LISTO\

REM INTEGRACIÓN
if exist QUICK_START_30_MIN.md move QUICK_START_30_MIN.md 05_INTEGRACION_PASO_A_PASO\
if exist COPY_PASTE_CHECKLIST.md move COPY_PASTE_CHECKLIST.md 05_INTEGRACION_PASO_A_PASO\
if exist INTEGRACION_MERCADO_PAGO_COMPLETA.md move INTEGRACION_MERCADO_PAGO_COMPLETA.md 05_INTEGRACION_PASO_A_PASO\
if exist GUIA_INTEGRACION_BACKEND_BD.md move GUIA_INTEGRACION_BACKEND_BD.md 05_INTEGRACION_PASO_A_PASO\

REM BASE DE DATOS
if exist SCRIPT_BASE_DATOS_COMPLETO.sql move SCRIPT_BASE_DATOS_COMPLETO.sql 06_BASE_DATOS_SQL\
if exist QUERIES_PRACTICAS.sql move QUERIES_PRACTICAS.sql 06_BASE_DATOS_SQL\
if exist ENDPOINTS_API_COMPLETOS.md move ENDPOINTS_API_COMPLETOS.md 06_BASE_DATOS_SQL\

REM DOCUMENTACIÓN GENERAL
if exist INDICE_ANALISIS_COMPLETO.md move INDICE_ANALISIS_COMPLETO.md 07_DOCUMENTACION_GENERAL\
if exist INDICE_DOCUMENTACION_FINAL.md move INDICE_DOCUMENTACION_FINAL.md 07_DOCUMENTACION_GENERAL\
if exist ANALISIS_TECNICO_WEB_VS_MOBILE.md move ANALISIS_TECNICO_WEB_VS_MOBILE.md 07_DOCUMENTACION_GENERAL\
if exist RESUMEN_EJECUTIVO_BD.md move RESUMEN_EJECUTIVO_BD.md 07_DOCUMENTACION_GENERAL\
if exist TABLAS_REFERENCIA_RAPIDA.md move TABLAS_REFERENCIA_RAPIDA.md 07_DOCUMENTACION_GENERAL\
if exist GUIA_USUARIO_MOVIL_COMPLETA.md move GUIA_USUARIO_MOVIL_COMPLETA.md 07_DOCUMENTACION_GENERAL\
if exist GUIA_DESPLIEGUE_COMPLETO.md move GUIA_DESPLIEGUE_COMPLETO.md 07_DOCUMENTACION_GENERAL\
if exist CONFIRMACION_ACTUALIZACION_COMPLETA.md move CONFIRMACION_ACTUALIZACION_COMPLETA.md 07_DOCUMENTACION_GENERAL\

REM ARCHIVOS ANTERIORES - El resto
move ACTUALIZACION_GUIA_USUARIO.md 08_ARCHIVOS_ANTERIORES\
move CHECKLIST_IMPLEMENTACION_MOBILE.md 08_ARCHIVOS_ANTERIORES\
move COMPARACION_WEB_VS_MOBILE.md 08_ARCHIVOS_ANTERIORES\
move CONFIGURACION_BACKEND.env 08_ARCHIVOS_ANTERIORES\
move DETALLES_DE_CAMBIOS.md 08_ARCHIVOS_ANTERIORES\
move DOCUMENTOS_GENERADOS.md 08_ARCHIVOS_ANTERIORES\
move GUIA_IMPLEMENTACION_BD.md 08_ARCHIVOS_ANTERIORES\
move LISTA_ARCHIVOS_GENERADOS.md 08_ARCHIVOS_ANTERIORES\
move README_ACTUALIZACION.md 08_ARCHIVOS_ANTERIORES\
move README_JAMCONNECT.md 08_ARCHIVOS_ANTERIORES\
move RESUMEN_FINAL.txt 08_ARCHIVOS_ANTERIORES\
move RESUMEN_UNA_PAGINA.md 08_ARCHIVOS_ANTERIORES\
move RESUMEN_VISUAL_WEB_VS_MOBILE.md 08_ARCHIVOS_ANTERIORES\

echo ✅ Organización completada!
echo.
echo 📂 Carpetas creadas:
echo    01_INICIO_RAPIDO_LECTURA_INMEDIATA/
echo    02_PLANIFICACION_ROADMAP/
echo    03_CODIGO_FLUTTER_LISTO/
echo    04_CODIGO_BACKEND_LISTO/
echo    05_INTEGRACION_PASO_A_PASO/
echo    06_BASE_DATOS_SQL/
echo    07_DOCUMENTACION_GENERAL/
echo    08_ARCHIVOS_ANTERIORES/
echo.
pause
