// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqqK205vzYqb5HrJEzsl9jzKbn2pRuNc',
    appId: '1:375864472598:web:db0f213f9b40d80644b137',
    messagingSenderId: '375864472598',
    projectId: 'condicion-humano',
    authDomain: 'condicion-humano.firebaseapp.com',
    storageBucket: 'condicion-humano.firebasestorage.app',
    measurementId: 'G-WHZ1X4RLVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVf6fSM0l41lZZr8I_0fcr8hYzQyaqc90',
    appId: '1:375864472598:android:27f4df986f230bfd44b137',
    messagingSenderId: '375864472598',
    projectId: 'condicion-humano',
    storageBucket: 'condicion-humano.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA8kjlrGNf27MopV_b0fHzvbXgQMK1zUM',
    appId: '1:375864472598:ios:55b8296101cb417f44b137',
    messagingSenderId: '375864472598',
    projectId: 'condicion-humano',
    storageBucket: 'condicion-humano.firebasestorage.app',
    iosBundleId: 'com.example.humano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA8kjlrGNf27MopV_b0fHzvbXgQMK1zUM',
    appId: '1:375864472598:ios:55b8296101cb417f44b137',
    messagingSenderId: '375864472598',
    projectId: 'condicion-humano',
    storageBucket: 'condicion-humano.firebasestorage.app',
    iosBundleId: 'com.example.humano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLqqK205vzYqb5HrJEzsl9jzKbn2pRuNc',
    appId: '1:375864472598:web:6099e96e14c4001344b137',
    messagingSenderId: '375864472598',
    projectId: 'condicion-humano',
    authDomain: 'condicion-humano.firebaseapp.com',
    storageBucket: 'condicion-humano.firebasestorage.app',
    measurementId: 'G-SJE4GW3S2Z',
  );
}
